FROM node:14.19.0

RUN npm i -g --unsafe-perm node-sass gulp yo @microsoft/generator-sharepoint

VOLUME /usr/app/spfx
WORKDIR /usr/app/spfx
RUN useradd --create-home --shell /bin/bash spfx && \
    usermod -aG sudo spfx && \
    chown -R spfx:spfx /usr/app/spfx

USER spfx

CMD /bin/bash
